_extends: .github
repository:
  name: sonar-deploy-action
  description: Action to deploy to the Scoop release server
  topics: platform, sonar
  homepage: https://sonar.takescoop.com
branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_pull_request_reviews: null
