on:
  pull_request:
    branches: master
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup dependency cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm ci --production
    - name: Update dist
      run: npm run build
    - name: Commit dist
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "chore: publish dist" || echo "Nothing to commit"
        git push origin master
